app/Datavark/Datavark/urls.py
"""Datavark URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("ie.urls"), kwargs={}, name="ie"),
    path("data/", include("dataview.urls"), kwargs={}, name="dataview"),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

app/Datavark/dataview/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "dataview"
urlpatterns = [
    path("", views.ReportsView.as_view(), name="reports-view"),
    path("<int:id>", views.DetailView.as_view(), name="detail-view"),
    path("export", views.DataExportView.as_view(), name="data-export-view"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/Datavark/ie/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "ie"
urlpatterns = [
    path("", views.IEView.as_view(), name="index"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/Datavark/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Datavark{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}?v=5" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}?v=5" />
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <link rel="shortcut icon" href="{%  static 'img/favicon.ico' %}">
    {% block stylesheets %}{% endblock %}
    {% block head-scripts %}{% endblock %}
</head>

<body>
    <div id="sidebar">
        <div id="leftHeader">
            <a href="/">
                <div id="siteIcon">
                    <div id="iconContainer"><img src="{% static 'img/datavark_logo.png' %}"
                            alt="DatavArk - Automated Data Acquisition System" /></div>
                </div>
            </a>
            <div id="siteTitle">
                <h1>DatavArk</h1>
            </div>
        </div>
        {% block sidebar %}
        <nav>
            <h1 id="navTitle">Navigation</h1>
            <ul>
                <li><a class="btn btn-info" href="{% url 'ie:index' %}" role="button">Acquisition Scheduler</a>
                </li>
                <li><a class="btn btn-info" href="{% url 'dataview:reports-view' %}" role="button">View Data</a></li>
                <li><a class="btn btn-info" href="{% url 'dataview:data-export-view' %}" role="button">Export Data</a>
                </li>
            </ul>
            <div id="backLink">
                <a class="btn btn-primary" href="{{request.META.HTTP_REFERER}}" role="button">Back</a>
            </div>
        </nav>
        {% endblock %}
    </div>
    <div id="content">
        <div id="pageTitle">{% block page_title %}{%endblock%}</div>
        {% block content %}{% endblock %}
    </div>
    <div id="footer">
        {% block footer %}Developed by Dan Bright, 12004727@uhi.ac.uk{% endblock %}
    </div>
</body>

{% block javascript %}{% endblock javascript %}

</html>